/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.sil.sga.interfaces;

import edu.sil.sga.dao.ClaseDAO;
import edu.sil.sga.dao.MatriculaDAO;
import edu.sil.sga.entidades.Alumno;
import edu.sil.sga.entidades.Clase;
import edu.sil.sga.entidades.DetalleMatricula;
import edu.sil.sga.entidades.Grado;
import edu.sil.sga.entidades.Matricula;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author Eduardo Lopez
 */
public class Admi_Matricula extends javax.swing.JInternalFrame {

    /**
     * Creates new form Admi_Matricula
     */
    Grado objGrado;
    Alumno objAlumno;
    ArrayList<DetalleMatricula> listaDetalleMatricula = new ArrayList<DetalleMatricula>();
    public List<Clase> listaDeClases;

    public Admi_Matricula() {
        initComponents();
    }

    void cargarDatosAlumno(Alumno objAlumno) {

        this.objAlumno = objAlumno;
        //txtNombre.setText(objAlumno.getNombre());
        txtDatosAlumno.setText(objAlumno.getApellidopaterno() + " " + objAlumno.getApellidomaterno() + ", " + objAlumno.getNombre() + " - " + objAlumno.getDni());
        //txtApellidoMaterno.setText(objAlumno.getApellidomaterno());
        //txtDNI.setText(objAlumno.getDni());
    }

    void cargarDatosGrado(Grado objGrado) {

        this.objGrado = objGrado;
        txtGrado.setText("'"+objGrado.getnumeroGrado()+" "+objGrado.getSeccion().getDescripcion()+"' -"+objGrado.getNivel().getNombreCorto());
        //txtSeccion.setText(objGrado.getSeccion().getDescripcion());
        //txtNivel.setText(objGrado.getNivel().getNombreCorto());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtDatosAlumno = new javax.swing.JTextField();
        btnBuscarAlumno = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        txtGrado = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        btnBuscarGrado = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnGuardar = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        jLabel1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel1.setText("Registrar Matricula");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos de Alumno"));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setText("* Alumno:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));
        jPanel1.add(txtDatosAlumno, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, 270, -1));

        btnBuscarAlumno.setText("Buscar");
        btnBuscarAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarAlumnoActionPerformed(evt);
            }
        });
        jPanel1.add(btnBuscarAlumno, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 30, -1, -1));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos de Grado"));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel2.add(txtGrado, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, 220, -1));

        jLabel7.setText("* Grado Completo");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));

        btnBuscarGrado.setText("Buscar");
        btnBuscarGrado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarGradoActionPerformed(evt);
            }
        });
        jPanel2.add(btnBuscarGrado, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 30, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null}
            },
            new String [] {
                "Curso", "Docente"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(290, 290, 290)
                            .addComponent(jLabel1))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(30, 30, 30)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 570, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(30, 30, 30)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 560, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(30, 30, 30)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 670, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarGradoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarGradoActionPerformed
        // TODO add your handling code here:
        List<Grado> lstGrado = new ArrayList<>();
        Admi_buscarGrado form = new Admi_buscarGrado(null, true, lstGrado);
        form.setVisible(true);
        if (lstGrado.isEmpty()) {
            //Ventana se cerro sin seleccionar
        } else {
            Grado objGradoElegido = lstGrado.get(0);
            cargarDatosGrado(objGradoElegido);
            System.out.println("lo que llego es: " + objGradoElegido.getId());

            //ahora debo cargar la lista las clases
            ClaseDAO dao = new ClaseDAO();
            listaDeClases = dao.ListarClasesPorGrado(objGradoElegido);
            
            //probando que clases llegaron:
            for (int i = 0; i < listaDeClases.size(); i++) {
                System.out.println("el codigo de clase que llego es: "+listaDeClases.get(i).getId());
            }
            
            
        }
    }//GEN-LAST:event_btnBuscarGradoActionPerformed

    private void btnBuscarAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarAlumnoActionPerformed
        // TODO add your handling code here:
        List<Alumno> lstAlumno = new ArrayList<>();
        Admi_buscarAlumno form = new Admi_buscarAlumno(null, true, lstAlumno);
        form.setVisible(true);
        if (lstAlumno.isEmpty()) {
            //Ventana se cerro sin seleccionar
        } else {
            Alumno objAlumnoElegido = lstAlumno.get(0);
            cargarDatosAlumno(objAlumnoElegido);
            System.out.println("lo que llego es: " + objAlumnoElegido.getId());
        }
    }//GEN-LAST:event_btnBuscarAlumnoActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:

        //PRIMERO ----> insetar la cabecera de Matriculas
        Matricula matricula = new Matricula();
        MatriculaDAO dao = new MatriculaDAO();

        matricula.setGrado(objGrado);
        matricula.setAlumno(objAlumno);

        if (dao.RegistrarMatricula(matricula,listaDeClases )) {
            JOptionPane.showMessageDialog(this, "Se registro correctamente la Matricula con todo =D  ");

        } else {
            JOptionPane.showMessageDialog(this, "No pudimos registrar la MATRICULA por problemas internos =( ");
        }
    }//GEN-LAST:event_btnGuardarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarAlumno;
    private javax.swing.JButton btnBuscarGrado;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtDatosAlumno;
    private javax.swing.JTextField txtGrado;
    // End of variables declaration//GEN-END:variables
}
