/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.sil.sga.interfaces;

import edu.sil.sga.dao.CursoPorGradoDAO;
import edu.sil.sga.entidades.Curso;
import edu.sil.sga.entidades.CursoPorGrado;
import edu.sil.sga.entidades.Grado;
import java.util.ArrayList;
import java.util.List;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author Eduardo Lopez
 */
public class Admi_CursoPorGrado extends javax.swing.JInternalFrame {

    /**
     * Creates new form Admi_CursoPorGrado
     */
    Grado grado;
    Curso curso;
    ArrayList<CursoPorGrado> listaDeCursosPorGrado = new ArrayList<CursoPorGrado>();
    CursoPorGrado objCursoGradoSeleccionado;

    public Admi_CursoPorGrado() {
        initComponents();
        setLocation(300, 20);
        btnBuscarCurso.setEnabled(false);
    }

    void cargarDatosGrado(Grado objGrado) {
        this.grado = objGrado;
        txtGrado.setText(" ' " + objGrado.getnumeroGrado() + " - " + objGrado.getSeccion().getDescripcion() + " ' de " + objGrado.getNivel().getNombreCorto());
        //txtSeccion.setText(objGrado.getSeccion().getDescripcion());
        //txtNivel.setText(objGrado.getNivel().getNombreCorto());
    }

    void cargarDatosCurso(Curso objCurso) {
        this.curso = objCurso;
        txtCurso.setText(objCurso.getNombreLargo());
        //txtSeccion.setText(objGrado.getSeccion().getDescripcion());
        //txtNivel.setText(objGrado.getNivel().getNombreCorto());
    }

    void recargarJTABLE(CursoPorGrado objCursoPorGrado, int tipo) {

        if (tipo == 0) {
            listaDeCursosPorGrado.add(objCursoPorGrado);
        } else if (tipo == 1) {
            listaDeCursosPorGrado.remove(objCursoPorGrado);
        } else {
            listaDeCursosPorGrado.clear();
        }
        
        
        DefaultTableModel modelo1 = new DefaultTableModel();

        //modelo1.addColumn("Grado");
        modelo1.addColumn("Nombre Curso");

        for (CursoPorGrado objcursoPorGrado : listaDeCursosPorGrado) {
            modelo1.addRow(new String[]{
                //objcursoPorGrado.getGrado().getnumeroGrado() + "",
                objcursoPorGrado.getCurso().getNombreLargo() + ""
            });
        }
        tblCursoPorGrado.setModel(modelo1);

        txtCurso.setText("");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButton1 = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCursoPorGrado = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        btnBuscarCurso = new javax.swing.JButton();
        btnBuscarGrado = new javax.swing.JButton();
        txtCurso = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtGrado = new javax.swing.JTextField();
        btnEliminarCurso = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        btnNuevo = new javax.swing.JButton();
        btnAgregarCurso = new javax.swing.JButton();

        jRadioButton1.setText("jRadioButton1");

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        jLabel1.setText("Asignar cursos por grado");

        tblCursoPorGrado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre del Curso"
            }
        ));
        jScrollPane1.setViewportView(tblCursoPorGrado);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos del Grado y Curso"));

        btnBuscarCurso.setText("buscar");
        btnBuscarCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarCursoActionPerformed(evt);
            }
        });

        btnBuscarGrado.setText("buscar");
        btnBuscarGrado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarGradoActionPerformed(evt);
            }
        });

        txtCurso.setEditable(false);

        jLabel3.setText("* Curso:");

        jLabel2.setText("* Grado:");

        txtGrado.setEditable(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtGrado, javax.swing.GroupLayout.DEFAULT_SIZE, 202, Short.MAX_VALUE)
                    .addComponent(txtCurso))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnBuscarGrado, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnBuscarCurso, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(41, 41, 41))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtGrado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarGrado))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarCurso))
                .addGap(21, 21, 21))
        );

        btnEliminarCurso.setText("-");
        btnEliminarCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarCursoActionPerformed(evt);
            }
        });

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnNuevo.setText("Nuevo");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });

        btnAgregarCurso.setText("+");
        btnAgregarCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarCursoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnAgregarCurso)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnEliminarCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 434, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnNuevo)
                                .addGap(18, 18, 18)
                                .addComponent(btnGuardar)))
                        .addGap(0, 53, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(164, 164, 164)
                        .addComponent(jLabel1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAgregarCurso)
                    .addComponent(btnEliminarCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardar)
                    .addComponent(btnNuevo))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarGradoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarGradoActionPerformed
        // TODO add your handling code here:
        List<Grado> lstGrado = new ArrayList<>();
        Admi_buscarGrado form = new Admi_buscarGrado(null, true, lstGrado);
        form.setVisible(true);
        if (lstGrado.isEmpty()) {
            //Ventana se cerro sin seleccionar
        } else {
            Grado objGradoElegido = lstGrado.get(0);
            cargarDatosGrado(objGradoElegido);
            btnBuscarGrado.setEnabled(false);
            System.out.println("el ID del Grado que llego es: " + objGradoElegido.getId());
            btnBuscarCurso.setEnabled(true);
        }
    }//GEN-LAST:event_btnBuscarGradoActionPerformed

    private void btnBuscarCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarCursoActionPerformed

        List<Curso> lstCurso = new ArrayList<>();
        Admi_buscarCurso form = new Admi_buscarCurso(null, true, lstCurso);
        form.setVisible(true);
        if (lstCurso.isEmpty()) {
            //Ventana se cerro sin seleccionar
        } else {
            Curso objCursoElegido = lstCurso.get(0);
            cargarDatosCurso(objCursoElegido);
            System.out.println("el ID del curso que llego es: " + objCursoElegido.getId());
            btnAgregarCurso.setEnabled(true);
        }
    }//GEN-LAST:event_btnBuscarCursoActionPerformed

    private void btnAgregarCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarCursoActionPerformed

        CursoPorGrado objCursoPorGrado = new CursoPorGrado();

        objCursoPorGrado.setCurso(curso);
        objCursoPorGrado.setGrado(grado);

        recargarJTABLE(objCursoPorGrado, 0);

        btnAgregarCurso.setEnabled(false);

    }//GEN-LAST:event_btnAgregarCursoActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed

        CursoPorGradoDAO dao = new CursoPorGradoDAO();

        if (dao.RegistrarCursoPorGrado(listaDeCursosPorGrado)) {
            JOptionPane.showMessageDialog(this, "Se registro correctamente a la Clase :) ");
            txtGrado.setText("");
            btnBuscarGrado.setEnabled(true);
            btnBuscarCurso.setEnabled(false);
            recargarJTABLE(objCursoGradoSeleccionado, 2);
        } else {
            JOptionPane.showMessageDialog(this, "No lo pudimos registrar por problemas internos :( ");
        }


    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        // TODO add your handling code here:

        listaDeCursosPorGrado.clear();

        txtGrado.setText("");
        txtCurso.setText("");
        btnBuscarGrado.setEnabled(true);

        DefaultTableModel modelo1 = new DefaultTableModel();

        //modelo1.addColumn("Grado");
        modelo1.addColumn("Nombre del Curso");

        for (CursoPorGrado objcursoPorGrado : listaDeCursosPorGrado) {
            modelo1.addRow(new String[]{
                //objcursoPorGrado.getGrado().getnumeroGrado() + "",
                objcursoPorGrado.getCurso().getNombreLargo() + ""
            });
        }
        tblCursoPorGrado.setModel(modelo1);
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void btnEliminarCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarCursoActionPerformed
        // TODO add your handling code here:
        int fila = tblCursoPorGrado.getSelectedRow();
        if (fila != -1) {
            objCursoGradoSeleccionado = listaDeCursosPorGrado.get(fila);

            recargarJTABLE(objCursoGradoSeleccionado, 1);
        }
    }//GEN-LAST:event_btnEliminarCursoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarCurso;
    private javax.swing.JButton btnBuscarCurso;
    private javax.swing.JButton btnBuscarGrado;
    private javax.swing.JButton btnEliminarCurso;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblCursoPorGrado;
    private javax.swing.JTextField txtCurso;
    private javax.swing.JTextField txtGrado;
    // End of variables declaration//GEN-END:variables
}
