/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.sil.sga.interfaces;

import edu.sil.sga.dao.ClaseDAO;
import edu.sil.sga.dao.MatriculaDAO;
import edu.sil.sga.entidades.Alumno;
import edu.sil.sga.entidades.Clase;
import edu.sil.sga.entidades.DetalleMatricula;
import edu.sil.sga.entidades.Grado;
import edu.sil.sga.entidades.Matricula;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Cesar Lopez
 */
public class Admi_Matricula extends javax.swing.JInternalFrame {

    /**
     * Creates new form Admi_Matricula
     */
    Grado objGrado;
    Alumno objAlumno;
    ArrayList<DetalleMatricula> listaDetalleMatricula = new ArrayList<DetalleMatricula>();
    public List<Clase> listaDeClases = new ArrayList<Clase>();

    public Admi_Matricula() {
        setLocation(250, 50);
        initComponents();
    }

    void cargarDatosAlumno(Alumno objAlumno) {

        this.objAlumno = objAlumno;
        txtAlumno.setText(objAlumno.getApellidopaterno() + " " + objAlumno.getApellidomaterno() + ", " + objAlumno.getNombre());

    }

    void cargarDatosGrado(Grado objGrado) {

        this.objGrado = objGrado;
        txtGrado.setText("Grado: " + objGrado.getnumeroGrado()
                + " - Seccion: " + objGrado.getSeccion().getDescripcion()
                + " - Nivel: " + objGrado.getNivel().getNombreCorto());
        //txtSeccion.setText(objGrado.getSeccion().getDescripcion());
        //txtNivel.setText(objGrado.getNivel().getNombreCorto());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtAlumno = new javax.swing.JTextField();
        btnBuscarAlumno = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        txtGrado = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        btnBuscarGrado = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCursoDocente = new javax.swing.JTable();
        btnGuardar = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        jLabel1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel1.setText("Registrar Matricula");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos de Alumno"));

        jLabel3.setText("* Nombre Completo");

        txtAlumno.setEditable(false);

        btnBuscarAlumno.setText("Buscar");
        btnBuscarAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarAlumnoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(24, 24, 24)
                .addComponent(txtAlumno, javax.swing.GroupLayout.DEFAULT_SIZE, 212, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(btnBuscarAlumno)
                .addGap(23, 23, 23))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarAlumno))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos de Grado"));

        txtGrado.setEditable(false);

        jLabel7.setText("* Grado Completo");

        btnBuscarGrado.setText("Buscar");
        btnBuscarGrado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarGradoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addGap(34, 34, 34)
                .addComponent(txtGrado, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(btnBuscarGrado)
                .addGap(23, 23, 23))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtGrado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarGrado))
                .addGap(12, 12, 12))
        );

        tblCursoDocente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null}
            },
            new String [] {
                "Curso", "Docente"
            }
        ));
        jScrollPane1.setViewportView(tblCursoDocente);

        btnGuardar.setText("Matricular");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(21, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(147, 147, 147)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarGradoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarGradoActionPerformed
        // TODO add your handling code here:
        List<Grado> lstGrado = new ArrayList<>();
        Admi_buscarGrado form = new Admi_buscarGrado(null, true, lstGrado);
        form.setVisible(true);
        if (lstGrado.isEmpty()) {
            //Ventana se cerro sin seleccionar
        } else {
            Grado objGradoElegido = lstGrado.get(0);
            cargarDatosGrado(objGradoElegido);
            System.out.println("El codigo del grado que llego es ---->  " + objGradoElegido.getId());

            //ahora debo cargar la lista las clases de ESE grado
            ClaseDAO dao = new ClaseDAO();
            listaDeClases = dao.ListarClasesPorGrado(objGradoElegido);

            //probando que clases llegaron:
            for (int i = 0; i < listaDeClases.size(); i++) {
                System.out.println("el codigo de clase que llego es: " + listaDeClases.get(i).getId());
                System.out.println("el nombre LARGO del curso es: " + listaDeClases.get(i).getCursoGrado().getCurso().getNombreLargo());
                System.out.println("el nombre del DOCENTE es: " + listaDeClases.get(i).getDocente().getNombre());
                System.out.println("el Apellido Paterno del DOCENTE es: " + listaDeClases.get(i).getDocente().getApellidopaterno());
                System.out.println("el Apelido Materno del DOCENTE es: " + listaDeClases.get(i).getDocente().getApellidomaterno());
            }

            //debo llenar el JTABLE CURDO DOCENTE
            DefaultTableModel modelo1 = new DefaultTableModel();

            //modelo1.addColumn("id");
            modelo1.addColumn("Curso");
            modelo1.addColumn("Docente");

            for (Clase clase : listaDeClases) {
                modelo1.addRow(new String[]{
                    //nivel.getId() + "",
                    clase.getCursoGrado().getCurso().getNombreLargo() + "",
                    clase.getDocente().getApellidopaterno() + " "
                    + clase.getDocente().getApellidopaterno() + ", "
                    + clase.getDocente().getNombre()
                });
            }
            tblCursoDocente.setModel(modelo1);

        }
    }//GEN-LAST:event_btnBuscarGradoActionPerformed

    private void btnBuscarAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarAlumnoActionPerformed
        // TODO add your handling code here:
        List<Alumno> lstAlumno = new ArrayList<>();
        Admi_buscarAlumno form = new Admi_buscarAlumno(null, true, lstAlumno);
        form.setVisible(true);
        if (lstAlumno.isEmpty()) {
            //Ventana se cerro sin seleccionar
        } else {
            Alumno objAlumnoElegido = lstAlumno.get(0);
            cargarDatosAlumno(objAlumnoElegido);
            System.out.println("lo que llego es: " + objAlumnoElegido.getId());
        }
    }//GEN-LAST:event_btnBuscarAlumnoActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:

        //PRIMERO ----> insetar la cabecera de Matriculas
        if (txtAlumno.getText().equals("") || listaDeClases.isEmpty() ) {
            JOptionPane.showMessageDialog(null, "Debe ingresar los campos requeridos con (*) ", "ERROR", JOptionPane.ERROR_MESSAGE);
        } else {
            Matricula matricula = new Matricula();
            MatriculaDAO dao = new MatriculaDAO();

            matricula.setGrado(objGrado);
            matricula.setAlumno(objAlumno);

            if (dao.RegistrarMatricula(matricula, listaDeClases)) {
                txtAlumno.setText("");
                txtGrado.setText("");
                DefaultTableModel modelo1 = new DefaultTableModel();

                //modelo1.addColumn("id");
                modelo1.addColumn("Curso");
                modelo1.addColumn("Docente");
                tblCursoDocente.setModel(modelo1);
                //JOptionPane.showMessageDialog(this, "Se registro la matricula para el alumno " + objAlumno.getNombre());
                JOptionPane.showMessageDialog(null, "Se registro la matricula para el alumno " + objAlumno.getNombre(), "CORRECTO", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, "No pudimos registrar la MATRICULA por problemas internos =( ");
            }
        }
    }//GEN-LAST:event_btnGuardarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarAlumno;
    private javax.swing.JButton btnBuscarGrado;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblCursoDocente;
    private javax.swing.JTextField txtAlumno;
    private javax.swing.JTextField txtGrado;
    // End of variables declaration//GEN-END:variables
}
