/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.sil.sga.interfaces;

import edu.sil.sga.dao.AlumnoDAO;
import edu.sil.sga.dao.NotaDAO;
import edu.sil.siga.bean.Alumno;
import edu.sil.siga.bean.Clase;
import edu.sil.siga.bean.Docente;
import edu.sil.siga.bean.Nota;
import edu.sil.siga.bean.Periodo;
import edu.sil.siga.bean.TipoEvaluacion;
import java.util.List;
import javax.swing.JDesktopPane;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author Eduardo Lopez
 */
public class Docente_IngresarNotaClase extends javax.swing.JInternalFrame {

    /**
     * Creates new form Docente_IngresarNotaClase
     */
    
    Clase clase = new Clase();
    Periodo periodo = new Periodo();
    TipoEvaluacion tipoEval = new TipoEvaluacion();
    public List<Nota> listaDeNotas;
    JDesktopPane jdPrincipalDocente;
    Docente docente;

    public Docente_IngresarNotaClase(Docente objdocente, Clase objClase, TipoEvaluacion objTipoEval, Periodo objPeriodo, JDesktopPane jdPrincipalDocente) {
        initComponents();
        
        setLocation(280, 50);
        
        this.docente = objdocente;
        this.jdPrincipalDocente = jdPrincipalDocente;
        
        clase = objClase;
        periodo = objPeriodo;
        tipoEval = objTipoEval;

        lblCurso.setText(clase.getCursoGrado().getCurso().getNombreLargo());
        lblPeriodo.setText(periodo.getDescripcion());
        lblTipoEvaluacion.setText(tipoEval.getDescripcion());

        ListarNotas();

    }//fin del INIT COMPONENTS

    void ListarNotas() {
        try {
            NotaDAO dao = new NotaDAO();
            listaDeNotas = dao.ListarNotas(clase, periodo, tipoEval);
            DefaultTableModel modelo1 = new DefaultTableModel();

            modelo1.addColumn("Nombre Completo");
            modelo1.addColumn("NOTA");

            for (Nota objNota : listaDeNotas) {
                modelo1.addRow(new String[]{
                    objNota.getAlumno().getNombre() + " "
                    + objNota.getAlumno().getApellidopaterno() + ", "
                    + objNota.getAlumno().getApellidomaterno(),
                    objNota.getNota() + ""
                });
            }
            tblAlumnoNota.setModel(modelo1);
        } catch (Exception e) {
            System.out.println("ERROR - INTERFAZ - ALUMNO - LISTAR");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnGuardar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblAlumnoNota = new javax.swing.JTable();
        lblCurso = new javax.swing.JLabel();
        lblTipoEvaluacion = new javax.swing.JLabel();
        lblPeriodo = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Ingresar Notas - I.E.P.San Ignacio de Loyola");

        jLabel1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel1.setText("Ingresar Notas");

        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/btnGuardar.png"))); // NOI18N
        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        tblAlumnoNota.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null}
            },
            new String [] {
                "Title 1", "Title 2"
            }
        ));
        jScrollPane1.setViewportView(tblAlumnoNota);

        lblCurso.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblCurso.setText("curso");

        lblTipoEvaluacion.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblTipoEvaluacion.setText("tipo eval");

        lblPeriodo.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblPeriodo.setText("periodo");

        jLabel2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel2.setText("Curso:");

        jLabel3.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel3.setText("Tipo de Nota:");

        jLabel4.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel4.setText("Bimestre:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblCurso)
                                .addGap(62, 62, 62)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblTipoEvaluacion)
                                .addGap(50, 50, 50)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblPeriodo))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnGuardar)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(235, 235, 235)
                        .addComponent(jLabel1)))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1)
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblCurso)
                        .addComponent(jLabel2))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblTipoEvaluacion)
                        .addComponent(jLabel3)
                        .addComponent(jLabel4)
                        .addComponent(lblPeriodo)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnGuardar)
                .addGap(31, 31, 31))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
        Nota nota = new Nota();
        NotaDAO dao = new NotaDAO();

        TableModel model = tblAlumnoNota.getModel();
        
        for (int i = 0; i < listaDeNotas.size(); i++) {
            listaDeNotas.get(i).setNota(Integer.parseInt(model.getValueAt(i, 1).toString()));
            
            System.out.println("el alumno ---> "+listaDeNotas.get(i).getAlumno().getNombre()+" se asigno -->" + model.getValueAt(i, 1).toString()+" de nota");
            
        }

        if (dao.ActualizarNotas(listaDeNotas)) {
            JOptionPane.showMessageDialog(this, "Se Actualizaron correctamente las notas  =D  ");
            this.dispose();
            Docente_seleccionarClase frm = new Docente_seleccionarClase(docente, jdPrincipalDocente);
            jdPrincipalDocente.add(frm);
            frm.setVisible(true);
            
        } else {
            JOptionPane.showMessageDialog(this, "Problemas para actualizar las notas =(  ");
        }
    }//GEN-LAST:event_btnGuardarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCurso;
    private javax.swing.JLabel lblPeriodo;
    private javax.swing.JLabel lblTipoEvaluacion;
    private javax.swing.JTable tblAlumnoNota;
    // End of variables declaration//GEN-END:variables
}
